### ISSUE TITLE
Release v0.4.0-preview.10

### ISSUE THREAD

**Issue by favoyang** [Dreaming381/Latios-Framework#1]
Hi @Dreaming381 ,

Thanks for creating the awesome package. Would you please create a [Github Release](https://github.com/Dreaming381/Latios-Framework/releases) for `0.4.0-preview.10`? A common practice is adding `v` prefix to the semver, as `v0.4.0-preview.10`.

Then the package can be added to upcoming [openupm registry](https://openupm.com), which is a service that build package automatically from git tags that conform semver.

To add the package, please visit [https://openupm.com/packages/add/](https://openupm.com/packages/add/)

Favo Yang

**Comment by Dreaming381** [comment]
Thanks for bringing this to my attention. This is version 0.1.0 and I created a release for it. I haven't totally figured out this UPM stuff, so if you find something else I broke, let me know!

**Comment by favoyang** [comment]
@Dreaming381 

It works. [The package](https://openupm.com/packages/com.latios.latiosframework/) is added to openupm curated list, and published v0.1.0. Further GitHub releases will be published automatically.

Learn more about OpenUPM at https://openupm.com/docs/#introduction
