### ISSUE TITLE
Android Build Crash on Startup Error : Unable to load plugin `AclUnity`

### ISSUE THREAD

**Issue by DabManTrips** [Dreaming381/Latios-Framework#12]
Was trying to test Latios-Framework with DMotion on Android device. 
Crashes on startup with error: Unable to load plugin `AclUnity`

08-31 20:44:21.511: E/Unity(7372): Unable to load plugin `AclUnity`
08-31 20:44:21.511: E/Unity(7372): Unity.Burst.BurstCompilerHelper:IsCompiledByBurst(Delegate)
08-31 20:44:21.511: E/Unity(7372): Unity.Burst.BurstCompilerHelper:.cctor()
08-31 20:44:21.511: E/Unity(7372): Unity.Burst.BurstCompiler:Compile(Object, MethodInfo, Boolean, Boolean)
08-31 20:44:21.511: E/Unity(7372): Unity.Burst.BurstCompiler:CompileILPPMethod2(RuntimeMethodHandle)
08-31 20:44:21.511: E/Unity(7372): Unity.Collections.Try_00000A44$BurstDirectCall:Constructor()
08-31 20:44:21.511: E/Unity(7372): $BurstDirectCallInitializer:Initialize()

Edit: I'm looking into compiling the ACL plugin for android platform I'll update if this fixes the problem.

**Comment by Dreaming381** [comment]
Currently, only desktop Windows, Mac OS, and Linux platforms are supported. If you would like to extend support for Android, you'll need to build the plugin for Android: https://github.com/Dreaming381/AclUnity#adding-platform-support-for-the-latios-framework

Keep in mind that Hybrid Renderer performance on Android is often quite bad. Kinemation will only make the matter worse as it leverages code paths that typically perform poorly on lower-end mobile devices. It is rumored that these issues will be resolved in DOTS 1.0.

If you choose to attempt adding support for Android, feel free to reach out with any questions you may have!

**Comment by DabManTrips** [comment]
This is my first time I've done this so I'm teaching myself but I can't seem to get it right.
I don't know how to setup the CMakeList.txt for Android. If I understand correctly I put the original ACL into the acl folder?
I honestly don't know what I'm doing and could use some help.
