### ISSUE TITLE
FixedStepSimulationSystemGroup in Entities 0.16

### ISSUE THREAD

**Issue by ScriptsEngineer** [Dreaming381/Latios-Framework#2]
Is your FixedSimulationSystemGroup can be replaced by the new FixedStepSimulationSystemGroup of entities version 0.16?

**Comment by Dreaming381** [comment]
You can use either. FixedSimulationSystemGroup injects into the FixedUpdate cycle of the PlayerLoop (or at least it is supposed to, I would not be surprised if it broke) and so it should tick once after each FixedUpdate tick in all the MonoBehaviours. FixedStepSimulationSystemGroup updates independently inside SimulationSystemGroup using its own fixed-rate mechanism.

If you are not using GameObjects that need classical FixedUpdate, I would use FixedStepSimulationSystemGroup as it is better vetted.
