### ISSUE TITLE
Compilation errors when ENABLE_TRANSFORM_V1 is not defined

### ISSUE THREAD

**Issue by laicasaane** [Dreaming381/Latios-Framework#20]
Will Latios still depend on Transform V1 in the future? Because Unity said they will remove V1 soon.

**Comment by laicasaane** [comment]
> Latios Transforms – A novel QVVS transform system designed to be fast, intuitive, and flexible (Coming in 0.7)

I've just read this. Does it mean in the future Latios won't depend on Unity Transforms anymore?

**Comment by Dreaming381** [comment]
Latios Framework 0.6.x only supports V1, and this has been outlined in the documentation along with steps to avoid this compilation error. This decision was made for several reasons:

- The jump between 0.5 and 0.6 was already fairly significant with a lot of breaking changes (mostly Entities 0.51 to 1.0), and I didn't want to push too much at once
- At the time, Physics and NetCode still exclusively used V1, and there was no telling when they would switch
- V2 cannot physically represent a style of animation that is a hard requirement I have for Kinemation

As you have pointed out, 0.7 will not depend on Unity Transforms and instead use a custom solution. It will be up to the community to add Unity Transforms V2 support if they find it valuable.

If you have questions or concerns regarding the current plan, feel free to leave them here or one of the other communication channels.

**Comment by laicasaane** [comment]
Thanks for the explanation. I only want to understand your plan. V1 or V2 isn't much of a problem to me currently. I'm only in the process of learning things around Unity ECS APIs.
