### ISSUE TITLE
Compiler Errors with Entities 1.0.0-pre.15

### ISSUE THREAD

**Issue by Adrodoc** [Dreaming381/Latios-Framework#25]
I am upgrading my project to Entities 1.0.0-pre.15. Unfortunately Latios Framework has a bunch of compiler errors. This is weird, because the way I understand it Entities 1.0.0-pre.15 should be supported since Latios Framework version [0.6.1](https://github.com/Dreaming381/Latios-Framework/releases/tag/v0.6.1).

I am using Unity 2022.2.2f1 and added Latios through the Package Manager via git URL: https://github.com/Dreaming381/Latios-Framework.git
This installed version 0.6.4.

These are the errors I get:
```
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(18,25): error CS0246: The type or namespace name 'TRSToLocalToParentSystem' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(19,25): error CS0246: The type or namespace name 'TRSToLocalToWorldSystem' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(20,26): error CS0246: The type or namespace name 'LocalToParentSystem' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ImprovedTransforms\ImprovedLocalToParentSystem.cs(20,25): error CS0246: The type or namespace name 'TRSToLocalToParentSystem' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ImprovedTransforms\ImprovedLocalToParentSystem.cs(21,25): error CS0246: The type or namespace name 'TRSToLocalToWorldSystem' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ImprovedTransforms\ImprovedLocalToParentSystem.cs(22,26): error CS0246: The type or namespace name 'LocalToParentSystem' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(36,29): error CS0246: The type or namespace name 'LocalToParent' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ImprovedTransforms\ImprovedLocalToParentSystem.cs(175,40): error CS0246: The type or namespace name 'LocalToParent' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(155,40): error CS0246: The type or namespace name 'LocalToParent' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ImprovedTransforms\ImprovedLocalToParentSystem.cs(37,47): error CS0246: The type or namespace name 'LocalToParent' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(284,51): error CS0246: The type or namespace name 'LocalToParent' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(344,51): error CS0246: The type or namespace name 'LocalToParent' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.latios.latiosframework@65ad140350\Core\Systems\Transforms\ExtremeHierarchy\ExtremeLocalToParentSystem.cs(382,47): error CS0246: The type or namespace name 'LocalToParent' could not be found (are you missing a using directive or an assembly reference?)
```

As far as I can tell the referenced types `TRSToLocalToParentSystem`, `TRSToLocalToWorldSystem`, `LocalToParentSystem` and `LocalToParent` do indeed not exist in Entities 1.0.0-pre.15 anymore.

**Comment by Dreaming381** [comment]
The third line of the README states the following:
_The 0.6.x series uses Transforms V1, which can be enabled in your project via the Scripting Define Symbol ENABLE_TRANSFORM_V1. If you are using Transforms V2, please wait for a newer version of the Latios Framework._

It is worth noting that the information in the README is a little out-of-date, in that 0.7 will be switching away from Unity Transforms entirely due to crippling restrictions with Transforms V2. But with 0.6.4 today, you need that scripting define symbol, and the component types will start to exist again. The latest LSSS master is using Entities pre.15 if you need an example.

**Comment by Morphexe** [comment]
Since V0.7 is moving away from unity transforms - is there any way to make system build with those transforms in mine work with LATIOS?

For example, the RIVAL character controller uses TransformsV2, will there be a way to make them compatible or run in parallel?

**Comment by Dreaming381** [comment]
If there does become a way for them to be compatible, it would be a community-driven solution. I don't have a good grasp of the use cases to make any promises.

**Comment by Dreaming381** [comment]
Docs? No.

Written answers to questions on Discord, forum PMs, GitHub discussions, or wherever else? Absolutely!

I believe Latios Transforms will have feature parity with Unity Transforms V2 from a practical standpoint. However, Unity Transforms will not have feature parity with Latios Transforms. In other words, Unity Transforms will be missing features that Kinemation uses in 0.7.

**Comment by Morphexe** [comment]
Thats ok, and not what I was expecting. Having parity with V2 would be enough to convert most of the stuff from V2 to Latios.  Kinemation is the biggest reason why I am waiting for V2 parity, Kinemation + Rival seems a nice setup to get started :)

**Comment by Dreaming381** [comment]
Closing as 0.7 is released along with the new QVVS Transforms. If you have any issues with the new system, feel free to reach out!
