### ISSUE TITLE
World/Scene "ScopedEntity"

### ISSUE THREAD

**Issue by michal-ciechan** [Dreaming381/Latios-Framework#3]
> Re: Feedback Request: I am looking for a better term than “global” to describe these entities. “World” + “Global” sounds redundant and simultaneously confusing when the “Scene” variant comes into play.

What is common in LOB software development (At least in the .NET world) is for IoC containers to have scopes such as:

* SingletonScope
* ContainerScope
* RequestScope
* TransientScope

So you could potentially rename that. 

P.B. wasn't sure where you'd prefer the feedback, her or unity forums. Feel free to comment + close!

**Comment by Dreaming381** [comment]
Either location works, although I see forum posts much sooner.

To me, "Scope" implies lifetime. And in this case, many entities can have a scene or world lifetime (based on whether the DontDestroyOnSceneChangeTag is present).

I think I am looking for a word that replaces "singleton" without directly being a reference to an OOP pattern.

Thanks for the suggestion! I will keep this open in case you or others have more ideas!

**Comment by Dreaming381** [comment]
I went with `BlackboardEntity`.
