### ISSUE TITLE
Path to shader library in the Kinemation Shader graph nodes should not contain a hyphen in the package name.

### ISSUE THREAD

**Issue by ashwin911** [Dreaming381/Latios-Framework#33]
https://github.com/Dreaming381/Latios-Framework/blob/2cbb49097ae635b8de53cf81e8f9dee1516b863c/Kinemation/Editor/ExtraShaderGraphNodes/LatiosDeformNode.cs#L154

the hyphen makes it unfindable for the shader.

**Comment by Dreaming381** [comment]
Thanks for reporting. This issue should be fixed now in 0.7.1
