### ISSUE TITLE
FYI Compound Colliders broke in Entities 0.17

### ISSUE THREAD

**Issue by djsell** [Dreaming381/Latios-Framework#4]
Compound collider generation seems broken with the new validation rules for Blob Assets in Entities 0.17

I don't need them, so I just commented it out :-P

```Assets/Scripts/Latios/Physics/Physics/Authoring/LatiosColliderConversionSystem.cs(298,17): error ConstructBlobWithRefTypeViolation: You may not build a type CompoundColliderBlob with Construct as CompoundColliderBlob.colliders[].m_blobRef.m_data.m_Ptr is a reference or pointer.  Only non-reference types are allowed in Blobs.```

Related-ish:
https://forum.unity.com/threads/entities-0-17-changelog.1020202/page-2#post-6757510

**Comment by Dreaming381** [comment]
Thank you for reporting this.

I believe this has already been fixed in the [0.2.2] patch release that went out this last weekend. If you are still seeing the issue in [0.2.2], let me know and I will definitely look into it further!

It is worth noting that [0.2.2] contains some subscene-related fixes based on the new documentation.

It is also worth noting that I have not migrated LSSS to Entities [0.17.0] yet. I will do that once I test and debug the new audio system.

**Comment by djsell** [comment]
Oh, alright.  Thanks.   I should've checked that before reporting.  I haven't brought in the 0.2.2 changes to my own project yet, as I am lazy.  I maintain a fork because I actually use it in Tiny and some things didn't work with it.  I also have some things I added for myself, such as running a single collider vs a layer from inside a job and simple raycasting.

**Comment by Dreaming381** [comment]
No worries!

Your fork sounds awesome by the way! Almost everything you describe implementing yourself are backlog features. However, there is one thing I am curious about.

Is there a reason you are not using `BuildCollisionLayer.RunImmediate` and `FindPairs.RunImmediate` for testing a single collider against a layer inside a job?

**Comment by djsell** [comment]
Just didn't want the overhead(? my assumption - didn't test) of building a whole layer for one collider in order to test it against another layer.

As an example, I have units that have a presence emitter, and I have units that have a presence sensor.  An AI unit with a sensor does not need to scan for a new target every frame.  So unless the current AI operation says to find an enemy, the sensor system can early out for that unit.  Otherwise, it will test that single collider vs the emitter layer.

In another system, I can't remember the exact situation atm, it was also faster to do it this way as scheduling FindPairs had poor performance for layer vs layer due to the cross buckets.  That was in the early days of me using it though, and I may have had bucket sizing off.  I did see you added ScheduleParallelUnsafe at some point, assuming the purpose was to alleviate that situation.

Hope my use cases help!  Glad to hear any ideas of better ways to do it as well.

**Comment by Dreaming381** [comment]
These are great use cases!

For the first case, while I do need a single-item query API, I also need a BuildCollisionLayer that lets you enqueue entities to add in parallel. I was hoping that the new entity array filters would handle this, but they don't work async. Your temporary solution makes sense.

As for performance with the cross buckets, yes. That is what ScheduleParallelUnsafe is for until I implement stream caches. If you ever run into performance issues in the future, don't hesitate to make optimization requests, especially if you believe they outweigh new features!

One last thing, if you ever want to see some of your changes potentially make it back into the framework and be credited either by your preferred tag or anonymously but don't want to spend the time making a pull request, I accept zip files to my email dreamingimlatios@gmail.com. Of course if you don't feel like sharing, that's fine too. You have already been super helpful!

Thanks for all the feedback and insight!

**Comment by djsell** [comment]
Sounds good.  Whenever I get around to merging the latest in, I'll clean mine up a bit as well and send it your way.
