### ISSUE TITLE
Exceptions pop up on modification to package. Cleared when editor is restarted.

### ISSUE THREAD

**Issue by AVeryLostNomad** [Dreaming381/Latios-Framework#9]
Hi, 

I've cloned the package locally in my Packages folder based on the contents of the repository at the Version 0.5.1 release. It works well and as expected, but if I ever modify the code of the package Unity seems to "discover" several errors all at once. To be clear, these errors do **not** prevent me from running after a unity restart, and I can always clear them by restarting the editor. It's just getting tedious having to restart every time, so I figured I'd ask if this is something you knew about / had encountered and possibly if you had a workaround. 

The errors are all like this
` Cannot apply indexing with [] to an expression of type 'ChunkInstanceLodEnabled.<Enabled>e__FixedBuffer'`

But happen in various files 
`Packages\Latios-Framework-master\Kinemation\Systems\Culling\UpdateLODsSystem.cs(156,29): error CS0021: Cannot apply indexing with [] to an expression of type 'ChunkInstanceLodEnabled.<Enabled>e__FixedBuffer'`

`Packages\Latios-Framework-master\Kinemation\Systems\Culling\FrustumCullUnskinnedEntitiesSystem.cs(70,50): error CS0021: Cannot apply indexing with [] to an expression of type 'ChunkInstanceLodEnabled.<Enabled>e__FixedBuffer'`

`Packages\Latios-Framework-master\Kinemation\Systems\Culling\FrustumCullSkinnedEntitiesSystem.cs(69,85): error CS0021: Cannot apply indexing with [] to an expression of type 'ChunkInstanceLodEnabled.<Enabled>e__FixedBuffer'`
etc....

Have you ran into these at all? I'm on 2020.3.36f1 and DOTS 0.50 preview 2.

**Comment by Dreaming381** [comment]
Switch the API Compatibility Level of your project from .NET 4.x to .NET Standard 2.0

**Comment by AVeryLostNomad** [comment]
That does appear to solve it. Thank you much @Dreaming381
